# Generated by Django 3.2 on 2021-04-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210421_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
